<a href="https://colab.research.google.com/github/Mannish2012/Visualizing-EIA-Data/blob/main/Assignment5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
#library(dplyr)
library(huxtable)


Attaching package: ‘huxtable’


The following object is masked from ‘package:dplyr’:

    add_rownames




In [65]:
 a <- matrix(c(0,1,1,0,0,
              c(1,rep(0,4)),
              rep(0,5),
              rep(0,5),
              c(rep(0,3),1,0)),5,5) -> a0

Get the matrix in echelon form

In [66]:
as_hux(a0)

V1 V2 V3 V4 V5
1 0  1  0  0  0 
2 1  0  0  0  0 
3 1  0  0  0  0 
4 0  0  0  0  1 
5 0  0  0  0  0

In the above matrix, two columns (the third and fourth) are unnecessary, so we remove them. We also remove the last row. To this matrix, append a column of zeros to create the augmented matrix.

In [88]:
a_aug <- a0[-5,-c(3,4)] |> cbind(rep(0,4))
as_hux(a_aug)

V1 V2 V3 V4
1 0  1  0  0 
2 1  0  0  0 
3 1  0  0  0 
4 0  0  1  0

Now the get the matrix in rref.

In [89]:
a2 = a_aug[c(2,3,1,4),]; as_hux(a2)


V1 V2 V3 V4
1 1  0  0  0 
2 1  0  0  0 
3 0  1  0  0 
4 0  0  1  0

In [90]:
# forward pass, col 1
a2[2,] <- a2[1,] - a2[2,]
as_hux(a2)

V1 V2 V3 V4
1 1  0  0  0 
2 0  0  0  0 
3 0  1  0  0 
4 0  0  1  0

In [92]:
# rearrange
a2[c(1,3,4,2),] |> as_hux()


V1 V2 V3 V4
1 1  0  0  0 
2 0  1  0  0 
3 0  0  1  0 
4 0  0  0  0

Question 9

In [96]:
m <- matrix(c(
  0,1,0,0,0,
  0,1,0,0,0,
  1,0,0,0,0,
  1,0,0,0,0,
  0,0,1,0,0
),5,5, byrow = TRUE,
dimnames = list(c("Shubam","Poulami", "Asrifa", "Rafeal","Vicky"),
                c("1 star", "2 star", "3 star", "4 star", "5 star")))
as_hux(m)

1 star 2 star 3 star 4 star 5 star
Shubam  0      1      0      0      0     
Poulami 0      1      0      0      0     
Asrifa  1      0      0      0      0     
Rafeal  1      0      0      0      0     
Vicky   0      0      1      0      0

Question 7

In [100]:
a7 <- matrix(c(5,0,4,0,
            2,1,0,0,
            0,0,5,0,
            rep(0,4)),4,4) -> a7_0
as_hux(a7_0)

V1 V2 V3 V4
1 5  2  0  0 
2 0  1  0  0 
3 4  0  5  0 
4 0  0  0  0

In [116]:
a7 <- a7_0[c(1,3,2,4),]; as_hux(a7)

V1 V2 V3 V4
1 5  2  0  0 
2 4  0  5  0 
3 0  1  0  0 
4 0  0  0  0

In [117]:
a7 = rbind(a7[1,], 4*a7[1,] - 5*a7[2,], a7[3:4,])
a7

[,1] [,2] [,3] [,4]
[1,] 5    2      0  0   
[2,] 0    8    -25  0   
[3,] 0    1      0  0   
[4,] 0    0      0  0

In [118]:
a7 = rbind(a7[1:2,], a7[2,] - 8*a7[3,], a7[4,])
a7

[,1] [,2] [,3] [,4]
[1,] 5    2      0  0   
[2,] 0    8    -25  0   
[3,] 0    0    -25  0   
[4,] 0    0      0  0

In [120]:
#a7 = sweep(a7,1,c(5,8,-25,1),"/")
as_hux(a7)

V1 V2  V3     V4
1 1  0.4  0.000 0 
2 0  1.0 -3.125 0 
3 0  0.0  1.000 0 
4 0  0.0  0.000 0

In the above matrix $x_1 = -0.4x_2$, $x_2 = 3.125x_3$, $x_3 = 0$, which implies that all values are zero.

An explicit description of Nul A

In [18]:
a <- matrix(c(
  -3,6,-1,1,-7,
  1,-2,2,3,-1,
  2,-4,5,8,-4
),3,5, byrow=T) -> a0

# reduce a to rref

a <- a0[c(1,3,2),]
a <- rbind(a[1,], 2*a[1,] + 3*a[2,], a[1,] + 3*a[3,])
a

[,1] [,2] [,3] [,4] [,5]
[1,] -3   6    -1    1    -7 
[2,]  0   0    13   26   -26 
[3,]  0   0     5   10   -10

Sum #

In [67]:
a <- a0[c(2,3,1,4,5),]; as_hux(a)

V1 V2 V3 V4 V5
1 1  0  0  0  0 
2 1  0  0  0  0 
3 0  1  0  0  0 
4 0  0  0  0  1 
5 0  0  0  0  0

In [68]:
a[2,] <- a[1,] - a[2,]; as_hux(a) # forward pass on col 1

V1 V2 V3 V4 V5
1 1  0  0  0  0 
2 0  0  0  0  0 
3 0  1  0  0  0 
4 0  0  0  0  1 
5 0  0  0  0  0

The above matrix is not in rref because the zero rows are not at the bottom. Do that.

In [69]:
a -> a2 # create a temp matrix from which we can index the required rows
a <- a2[c(1,3,4,2,5),];

V1 V2 V3 V4 V5
1 1  0  0  0  0 
2 0  1  0  0  0 
3 0  0  0  0  1 
4 0  0  0  0  0 
5 0  0  0  0  0

In the augmented matrix below (augmented with an additional column of zeros), we note the solutions. $x_1$, $x_3$ and $x_5$ are all $0$, and the remaining variables, viz $x_3$ and $x_5$ are free.

In [70]:
 as_hux(cbind(a, rep(0,5)))

V1 V2 V3 V4 V5 V6
1 1  0  0  0  0  0 
2 0  1  0  0  0  0 
3 0  0  0  0  1  0 
4 0  0  0  0  0  0 
5 0  0  0  0  0  0

In [71]:
 as_hux(cbind(a[-c(4,5),], rep(0,3)))

V1 V2 V3 V4 V5 V6
1 1  0  0  0  0  0 
2 0  1  0  0  0  0 
3 0  0  0  0  1  0

In [82]:
 as_hux(cbind(a[-c(4,5),-c(3,4)]) |> cbind(c(0,0,0)))

V1 V2 V3 V4
1 1  0  0  0 
2 0  1  0  0 
3 0  0  1  0

Now the matrix is in rref, and we notice that the pivot variables are $x_1$, $x_2$ and $x_5$.

In [64]:
as_hux(a0)

V1 V2 V3 V4 V5
1 0  1  0  0  0 
2 1  0  0  0  0 
3 1  0  0  0  0 
4 0  0  0  0  1 
5 0  0  0  0  0

In [73]:
det(a0)

[1] 0

The above matrix is in rref, and hence 1st, 2nd and 5th columns are pivot columns, and hence they form a basis for the column space or R, the echelon form matrix. Hence, in the original matrix, A, columns corresponding to the same column numbers will form the basis for the column space of A.

For the nullspace of A, we solve $A_{red}\textbf{x} = \textbf{0}$ by expressing each of the **pivot** variables in terms of **nonpivot** variables.

In the exercise, $x_1, x_2, x_4$ are the pivots, whereas $x_3,x_5$ are free. Solving, we get:
$x_1 = x_2 = x_4 = 0$ and



In [16]:
a0[,c(1,2,5)]

[,1] [,2] [,3]
[1,] 0    1    0   
[2,] 1    0    0   
[3,] 1    0    0   
[4,] 0    0    1   
[5,] 0    0    0

In [22]:
a = matrix(c(5,0,4,0,
2,1,0,0,
0,0,5,0,
rep(0,4)),4,4) -> a0

In [23]:
a = a0[c(1,3,2,4),]

In [24]:
a <- rbind(a[1,], 4*a[1,] - 5*a[2,], a[3:4,])
a <- rbind(a[1:2,], a[2,] - 8*a[3,], a[4,])

In [26]:
a <- rbind(a[2,] - 4*a[1,], a[2:4,])


[,1] [,2] [,3] [,4]
[1,] -20  0    -25  0   
[2,]   0  8    -25  0   
[3,]   0  0    -25  0   
[4,]   0  0      0  0

In [27]:
c(-1/20,1/8,-1/25,1)*a

[,1] [,2] [,3]   [,4]
[1,] 1    0     1.250 0   
[2,] 0    1    -3.125 0   
[3,] 0    0     1.000 0   
[4,] 0    0     0.000 0

$\begin{matrix}
4 & 0 & 5 & 0 \\
0 & 8 & -25 & 0 \\
0 & 0 & -25 & 0 \\
0 & 0 & 0 & 0 \\
\end {matrix}$



In [4]:
m <- matrix(c(2,1,-6,-2,0,
              0,1,6,-2,0,
              0,0,24,-2,0),byrow = TRUE, 3,5)

In [5]:
(m <- rbind(m[3,] + 4*m[1,],
          m[3,] - 4*m[2,],
          m[3,]))

[,1] [,2] [,3] [,4] [,5]
[1,] 8     4    0   -10  0   
[2,] 0    -4    0     6  0   
[3,] 0     0   24    -2  0

In [6]:
(m <- rbind(m[2,] + m[1,], m[2:3,]))

[,1] [,2] [,3] [,4] [,5]
[1,] 8     0    0   -4   0   
[2,] 0    -4    0    6   0   
[3,] 0     0   24   -2   0

In [10]:
sweep(m,1,c(8,-2,2),"/")

[,1] [,2] [,3] [,4] [,5]
[1,] 1    0     0   -0.5 0   
[2,] 0    2     0   -3.0 0   
[3,] 0    0    12   -1.0 0

In [8]:
1/.083

[1] 12.04819